// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA98-MBL6N058lQ3lUVXbOpibIVCDudAL8',
    appId: '1:238898270944:web:bc2c2bffef3bb79b423685',
    messagingSenderId: '238898270944',
    projectId: 'store-7e8d7',
    authDomain: 'store-7e8d7.firebaseapp.com',
    storageBucket: 'store-7e8d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEXtz1eqIvwOiON_ZX2qImmiOHNoyd2ZI',
    appId: '1:238898270944:android:e64f11843ebfca9c423685',
    messagingSenderId: '238898270944',
    projectId: 'store-7e8d7',
    storageBucket: 'store-7e8d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmYmU4vFJ9LtIaA1WeZ6YVlvxkTpIeoxg',
    appId: '1:238898270944:ios:701380d5843f1ebb423685',
    messagingSenderId: '238898270944',
    projectId: 'store-7e8d7',
    storageBucket: 'store-7e8d7.appspot.com',
    iosBundleId: 'com.example.store',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmYmU4vFJ9LtIaA1WeZ6YVlvxkTpIeoxg',
    appId: '1:238898270944:ios:701380d5843f1ebb423685',
    messagingSenderId: '238898270944',
    projectId: 'store-7e8d7',
    storageBucket: 'store-7e8d7.appspot.com',
    iosBundleId: 'com.example.store',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA98-MBL6N058lQ3lUVXbOpibIVCDudAL8',
    appId: '1:238898270944:web:309c252cf13c4c2d423685',
    messagingSenderId: '238898270944',
    projectId: 'store-7e8d7',
    authDomain: 'store-7e8d7.firebaseapp.com',
    storageBucket: 'store-7e8d7.appspot.com',
  );
}
